### ISSUE TITLE
Avast detected its a virus?!

### ISSUE THREAD

**Issue by UKI-COMPUTERS** [Proxlight/Proxlight-Designer-v2#1]
Please help me! When run a Proxlite designer, Avast moves Proxiite designer to quarantine beacuse is infected with Win32:MalwareGen. If this sure?

**Comment by Proxlight** [comment]
Proxlight Designer has been created by pyinstaller and it is 100% safe I have scanned it in over 3 Antiviruses and they even approved it, I have not found any virus in Proxlight Designer. Around 1000 people using this tool and found it really safe and secure. Here is the screenshot by Quick Heal Pro 2021
![Virus](https://user-images.githubusercontent.com/69844328/131236354-d392bfb4-8db8-4540-b8e8-2a5400876b82.png)
