### ISSUE TITLE
UI Bad design

### ISSUE THREAD

**Issue by EgyptianM** [Proxlight/Proxlight-Designer-v2#10]
![image](https://user-images.githubusercontent.com/12565380/192630343-34f7bcc9-ffd4-4cba-bade-6a470e3b2ad8.png)

Who designed this UI?
I can't see a single word here, what the heck is that?

**Comment by Proxlight** [comment]
Use glasses man, in the video we have described each and everything properly.

**Comment by Proxlight** [comment]
Team Proxlight
