### ISSUE TITLE
New version of Proxilight is not there in the "Proxlight Designer Desktop Application" folder

### ISSUE THREAD

**Issue by zaid-ahmad** [Proxlight/Proxlight-Designer-v2#12]

**Comment by Proxlight** [comment]
Working on it

**Comment by HakoNguyen** [comment]
![Ảnh chụp màn hình 2023-12-19 210356](https://github.com/Proxlight/Proxlight-Designer-v2/assets/153352970/2799cd18-6cb3-4af5-925d-7cd692d8d0f0)
when i use proxlight, it only shows the frame not my contents.  what can i do ? i really need a help
