### ISSUE TITLE
It would be nice to add `ttk.Combobox`

### ISSUE THREAD

**Issue by joao-vitor-souza** [Proxlight/Proxlight-Designer-v2#14]
How hard would it be to implement the conversion of [ttk.ComboBox](https://docs.python.org/3/library/tkinter.ttk.html#combobox)? It works like a dropdown and it's a subclass of `Entry`, which is already implemented. Are there any plans to add more elements? I could work on this!

**Comment by Proxlight** [comment]
Sure

**Comment by Proxlight** [comment]
Yes you can add it

**Comment by joao-vitor-souza** [comment]
Nvm, I implemented it, but tbh it looks very ugly, it does not have parameteres like `highlightthickness` or `bg`. `OptionMenu`, which is another dropdown element from Tkinter, also doesn't have them. So, it's not worth it to put this in production.

**Comment by Proxlight** [comment]
Ok
