### ISSUE TITLE
THIS IS MALWARE

### ISSUE THREAD

**Issue by fazelastblood** [Proxlight/Proxlight-Designer-v2#3]
DONT DOWNLOAD

**Comment by fazelastblood** [comment]
THIS IS MALWARE DO NOT DOWNLOAD

**Comment by joelbarranteswins** [comment]
[Proxlight-Designer-v2](https://github.com/Proxlight/Proxlight-Designer-v2) 
this software doesn't work for me.

**Comment by LucBerge** [comment]
Proxilight is a fork of [Tkinter-Designer](https://github.com/ParthJadhav/Tkinter-Designer) which is safe

**Comment by simonp862** [comment]
Flagged by some security scanned as High Risk,  Contain Win32/Uwamson.A!ml Wich is described as a Backdoor Trojan. Id have to pass unfortunately, not taking any risk.
