### ISSUE TITLE
I can't get python code via Proxlight

### ISSUE THREAD

**Issue by ohashi3399** [Proxlight/Proxlight-Designer-v2#8]
Hi, thanks for making great tools Proxlight-Designer-v2!
I am research engineer and main language is python. so I'm new to such tool for designer. I am making a lickert scale from figma.com shown as below.
![editor](https://user-images.githubusercontent.com/87519834/183797596-4398d420-1af6-44d3-a239-92144dcf281e.png)

After editing the above design, python script was generated named window.py by Proxlight Designer desktop app.
But only white page is shown since window.py only includes the code which generates white background. Bellow is the full code.
```
from tkinter import *


def btn_clicked():
    print("Button Clicked")


window = Tk()

window.geometry("928x1159")
window.configure(bg = "#ffffff")
canvas = Canvas(
    window,
    bg = "#ffffff",
    height = 1159,
    width = 928,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge")
canvas.place(x = 0, y = 0)

window.resizable(False, False)
window.mainloop()

```

Is there something like naming rule of each component such like "Background", "Textbox" in editor?
It would be very helpful if you could provide any advises or video instructions. I also watched your Youtube channel. good

**Comment by LucBerge** [comment]
Don't use proxilight, it's a malware. The source code is not on github.

The original repo is https://github.com/ParthJadhav/Tkinter-Designer. Use ot instead
